spring.application.name=nutra

# Logging configuration
logging.level.root=ERROR
logging.level.org.hibernate=ERROR

# SQLite configuration
spring.datasource.url=jdbc:sqlite:${user.home}/.nutra/nutra-bdd.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true